"""initial schema

Revision ID: 1e51a25ec3c0
Revises: 
Create Date: 2026-09-18 23:50:56.856007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e51a25ec3c0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('names_local', sa.JSON(), nullable=False),
    sa.Column('sub_categories', sa.JSON(), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('sdg', sa.JSON(), nullable=False),
    sa.Column('infra_index_field', sa.String(length=40), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('dataset_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_name', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=400), nullable=True),
    sa.Column('department', sa.String(length=160), nullable=True),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('data_date', sa.Date(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_frequency', sa.String(length=40), nullable=True),
    sa.Column('license', sa.String(length=120), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'STALE', 'SUPERSEDED', 'FAILED', name='dataset_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geographic_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('level', sa.Enum('COUNTRY', 'STATE', 'DISTRICT', 'SUB_DISTRICT', 'LOCALITY', name='geo_level'), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('centroid_lat', sa.Float(), nullable=True),
    sa.Column('centroid_lng', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('aliases', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['geographic_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_geo_level_name', 'geographic_entities', ['level', 'name'], unique=False)
    op.create_index(op.f('ix_geographic_entities_code'), 'geographic_entities', ['code'], unique=False)
    op.create_index(op.f('ix_geographic_entities_country_code'), 'geographic_entities', ['country_code'], unique=False)
    op.create_table('demographics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geo_id', sa.Integer(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('population_density', sa.Float(), nullable=True),
    sa.Column('literacy_rate', sa.Float(), nullable=True),
    sa.Column('urban_population_pct', sa.Float(), nullable=True),
    sa.Column('rural_population_pct', sa.Float(), nullable=True),
    sa.Column('children_pct', sa.Float(), nullable=True),
    sa.Column('elderly_pct', sa.Float(), nullable=True),
    sa.Column('mobile_penetration_pct', sa.Float(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('data_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset_metadata.id'], ),
    sa.ForeignKeyConstraint(['geo_id'], ['geographic_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demographics_geo_id'), 'demographics', ['geo_id'], unique=False)
    op.create_table('government_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('category_code', sa.String(length=32), nullable=False),
    sa.Column('geo_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=160), nullable=True),
    sa.Column('budget_inr', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'APPROVED', 'NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'STALLED', name='project_status'), nullable=False),
    sa.Column('planned_year', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('expected_completion', sa.Date(), nullable=True),
    sa.Column('actual_completion', sa.Date(), nullable=True),
    sa.Column('scheme', sa.String(length=160), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('data_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['category_code'], ['categories.code'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset_metadata.id'], ),
    sa.ForeignKeyConstraint(['geo_id'], ['geographic_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_government_projects_category_code'), 'government_projects', ['category_code'], unique=False)
    op.create_index(op.f('ix_government_projects_geo_id'), 'government_projects', ['geo_id'], unique=False)
    op.create_table('infrastructure_indices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geo_id', sa.Integer(), nullable=False),
    sa.Column('road_index', sa.Float(), nullable=True),
    sa.Column('water_index', sa.Float(), nullable=True),
    sa.Column('sanitation_index', sa.Float(), nullable=True),
    sa.Column('waste_index', sa.Float(), nullable=True),
    sa.Column('electricity_index', sa.Float(), nullable=True),
    sa.Column('lighting_safety_index', sa.Float(), nullable=True),
    sa.Column('healthcare_index', sa.Float(), nullable=True),
    sa.Column('education_index', sa.Float(), nullable=True),
    sa.Column('housing_index', sa.Float(), nullable=True),
    sa.Column('environment_index', sa.Float(), nullable=True),
    sa.Column('disaster_resilience_index', sa.Float(), nullable=True),
    sa.Column('irrigation_index', sa.Float(), nullable=True),
    sa.Column('connectivity_index', sa.Float(), nullable=True),
    sa.Column('welfare_access_index', sa.Float(), nullable=True),
    sa.Column('employment_index', sa.Float(), nullable=True),
    sa.Column('public_space_index', sa.Float(), nullable=True),
    sa.Column('overall_index', sa.Float(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('data_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset_metadata.id'], ),
    sa.ForeignKeyConstraint(['geo_id'], ['geographic_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infrastructure_indices_geo_id'), 'infrastructure_indices', ['geo_id'], unique=False)
    op.create_table('investment_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geo_id', sa.Integer(), nullable=False),
    sa.Column('category_code', sa.String(length=32), nullable=False),
    sa.Column('fiscal_year', sa.String(length=9), nullable=False),
    sa.Column('allocated_inr', sa.Float(), nullable=False),
    sa.Column('planned_inr', sa.Float(), nullable=False),
    sa.Column('spent_inr', sa.Float(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('data_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['category_code'], ['categories.code'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset_metadata.id'], ),
    sa.ForeignKeyConstraint(['geo_id'], ['geographic_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_plans_category_code'), 'investment_plans', ['category_code'], unique=False)
    op.create_index(op.f('ix_investment_plans_geo_id'), 'investment_plans', ['geo_id'], unique=False)
    op.create_table('national_priorities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('programme', sa.String(length=160), nullable=False),
    sa.Column('category_code', sa.String(length=32), nullable=False),
    sa.Column('is_priority_sector', sa.Boolean(), nullable=False),
    sa.Column('target_geo_ids', sa.JSON(), nullable=False),
    sa.Column('quantified_target', sa.String(length=300), nullable=True),
    sa.Column('sdg', sa.JSON(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('data_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['category_code'], ['categories.code'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_national_priorities_category_code'), 'national_priorities', ['category_code'], unique=False)
    op.create_table('request_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category_code', sa.String(length=32), nullable=False),
    sa.Column('geo_id', sa.Integer(), nullable=False),
    sa.Column('representative_problem', sa.Text(), nullable=True),
    sa.Column('centroid', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('unique_citizens', sa.Integer(), nullable=False),
    sa.Column('average_urgency', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_code'], ['categories.code'], ),
    sa.ForeignKeyConstraint(['geo_id'], ['geographic_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_clusters_category_code'), 'request_clusters', ['category_code'], unique=False)
    op.create_index(op.f('ix_request_clusters_geo_id'), 'request_clusters', ['geo_id'], unique=False)
    op.create_table('citizen_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_code', sa.String(length=12), nullable=False),
    sa.Column('channel', sa.Enum('WEB', 'VOICE', 'WHATSAPP', 'SMS', 'IVR', 'OFFICE', name='channel'), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('audio_path', sa.String(length=300), nullable=True),
    sa.Column('audio_mime', sa.String(length=60), nullable=True),
    sa.Column('declared_language', sa.String(length=8), nullable=True),
    sa.Column('citizen_hash', sa.String(length=64), nullable=True),
    sa.Column('submitted_lat', sa.Float(), nullable=True),
    sa.Column('submitted_lng', sa.Float(), nullable=True),
    sa.Column('submitted_geo_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('detected_language', sa.String(length=8), nullable=True),
    sa.Column('translated_text', sa.Text(), nullable=True),
    sa.Column('category_code', sa.String(length=32), nullable=True),
    sa.Column('secondary_category_code', sa.String(length=32), nullable=True),
    sa.Column('sub_category', sa.String(length=80), nullable=True),
    sa.Column('problem_description', sa.Text(), nullable=True),
    sa.Column('urgency_score', sa.Integer(), nullable=True),
    sa.Column('location_mention', sa.String(length=200), nullable=True),
    sa.Column('resolved_geo_id', sa.Integer(), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=False),
    sa.Column('affected_population_estimate', sa.Integer(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_raw', sa.JSON(), nullable=True),
    sa.Column('ai_model', sa.String(length=60), nullable=True),
    sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('spam_score', sa.Float(), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('processing_status', sa.Enum('RECEIVED', 'PROCESSING', 'PROCESSED', 'REVIEW_REQUIRED', 'FAILED', 'LANGUAGE_UNSUPPORTED', name='processing_status'), nullable=False),
    sa.Column('verification_status', sa.Enum('UNVERIFIED', 'APPROVED', 'CORRECTED', 'REJECTED', name='verification_status'), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_code'], ['categories.code'], ),
    sa.ForeignKeyConstraint(['cluster_id'], ['request_clusters.id'], ),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['citizen_requests.id'], ),
    sa.ForeignKeyConstraint(['resolved_geo_id'], ['geographic_entities.id'], ),
    sa.ForeignKeyConstraint(['submitted_geo_id'], ['geographic_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizen_requests_category_code'), 'citizen_requests', ['category_code'], unique=False)
    op.create_index(op.f('ix_citizen_requests_citizen_hash'), 'citizen_requests', ['citizen_hash'], unique=False)
    op.create_index(op.f('ix_citizen_requests_cluster_id'), 'citizen_requests', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_citizen_requests_processing_status'), 'citizen_requests', ['processing_status'], unique=False)
    op.create_index(op.f('ix_citizen_requests_resolved_geo_id'), 'citizen_requests', ['resolved_geo_id'], unique=False)
    op.create_index(op.f('ix_citizen_requests_tracking_code'), 'citizen_requests', ['tracking_code'], unique=True)
    op.create_index(op.f('ix_citizen_requests_verification_status'), 'citizen_requests', ['verification_status'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geo_id', sa.Integer(), nullable=False),
    sa.Column('category_code', sa.String(length=32), nullable=False),
    sa.Column('rec_type', sa.Enum('NEW_PROJECT', 'ACCELERATE_EXISTING', 'MONITOR_EXISTING', 'REVIEW_ALLOCATION', name='recommendation_type'), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('demand_score', sa.Float(), nullable=False),
    sa.Column('infrastructure_gap_score', sa.Float(), nullable=False),
    sa.Column('population_impact_score', sa.Float(), nullable=False),
    sa.Column('urgency_score', sa.Float(), nullable=False),
    sa.Column('policy_alignment_score', sa.Float(), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('existing_project_id', sa.Integer(), nullable=True),
    sa.Column('alignment_quadrant', sa.String(length=32), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('explanation_model', sa.String(length=60), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_code'], ['categories.code'], ),
    sa.ForeignKeyConstraint(['existing_project_id'], ['government_projects.id'], ),
    sa.ForeignKeyConstraint(['geo_id'], ['geographic_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_category_code'), 'recommendations', ['category_code'], unique=False)
    op.create_index(op.f('ix_recommendations_geo_id'), 'recommendations', ['geo_id'], unique=False)
    op.create_index(op.f('ix_recommendations_is_current'), 'recommendations', ['is_current'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('policymaker_id', sa.String(length=120), nullable=False),
    sa.Column('decision', sa.Enum('ACCEPT', 'DEFER', 'REJECT', name='decision_type'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_recommendation_id'), 'decisions', ['recommendation_id'], unique=False)
    op.create_table('impact_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('geo_id', sa.Integer(), nullable=False),
    sa.Column('category_code', sa.String(length=32), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_code'], ['categories.code'], ),
    sa.ForeignKeyConstraint(['geo_id'], ['geographic_entities.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recommendation_id')
    )
    op.create_table('verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('analyst_id', sa.String(length=120), nullable=False),
    sa.Column('action', sa.Enum('APPROVE', 'CORRECT', 'REJECT', name='verification_action'), nullable=False),
    sa.Column('field_name', sa.String(length=60), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['citizen_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verifications_request_id'), 'verifications', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verifications_request_id'), table_name='verifications')
    op.drop_table('verifications')
    op.drop_table('impact_baselines')
    op.drop_index(op.f('ix_decisions_recommendation_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_recommendations_is_current'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_geo_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_category_code'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_citizen_requests_verification_status'), table_name='citizen_requests')
    op.drop_index(op.f('ix_citizen_requests_tracking_code'), table_name='citizen_requests')
    op.drop_index(op.f('ix_citizen_requests_resolved_geo_id'), table_name='citizen_requests')
    op.drop_index(op.f('ix_citizen_requests_processing_status'), table_name='citizen_requests')
    op.drop_index(op.f('ix_citizen_requests_cluster_id'), table_name='citizen_requests')
    op.drop_index(op.f('ix_citizen_requests_citizen_hash'), table_name='citizen_requests')
    op.drop_index(op.f('ix_citizen_requests_category_code'), table_name='citizen_requests')
    op.drop_table('citizen_requests')
    op.drop_index(op.f('ix_request_clusters_geo_id'), table_name='request_clusters')
    op.drop_index(op.f('ix_request_clusters_category_code'), table_name='request_clusters')
    op.drop_table('request_clusters')
    op.drop_index(op.f('ix_national_priorities_category_code'), table_name='national_priorities')
    op.drop_table('national_priorities')
    op.drop_index(op.f('ix_investment_plans_geo_id'), table_name='investment_plans')
    op.drop_index(op.f('ix_investment_plans_category_code'), table_name='investment_plans')
    op.drop_table('investment_plans')
    op.drop_index(op.f('ix_infrastructure_indices_geo_id'), table_name='infrastructure_indices')
    op.drop_table('infrastructure_indices')
    op.drop_index(op.f('ix_government_projects_geo_id'), table_name='government_projects')
    op.drop_index(op.f('ix_government_projects_category_code'), table_name='government_projects')
    op.drop_table('government_projects')
    op.drop_index(op.f('ix_demographics_geo_id'), table_name='demographics')
    op.drop_table('demographics')
    op.drop_index(op.f('ix_geographic_entities_country_code'), table_name='geographic_entities')
    op.drop_index(op.f('ix_geographic_entities_code'), table_name='geographic_entities')
    op.drop_index('ix_geo_level_name', table_name='geographic_entities')
    op.drop_table('geographic_entities')
    op.drop_table('dataset_metadata')
    op.drop_table('categories')
    # ### end Alembic commands ###
